title: My blog
description: My journey in consulting
author: "Lukas Krappmann"

theme: minima

base_url: /

# Minima social links
github_username: krapluka
linkedin_username: lukas-krappmann-1438b6174
rss: rss

# Minima: show excerpts in the index
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages:
  - _pages/front.md
  - _pages/about.md
  - _pages/404.html

include:
    - _pages

exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock