title: My blog
description: My journey in IT & consulting
author: "Lukas Krappmann"

theme: minima

base_url: /

# Minima social links
github_username: krapluka
linkedin_username: lukas-krappmann-1438b6174
rss: rss

# Minima: show excerpts in the index
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

exclude: 
    - .gitignore
    - Gemfile
    - Gemfile.lock